# Generated by Django 4.1.5 on 2023-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_usuario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='categoria',
            field=models.CharField(choices=[('P', 'Programação'), ('G', 'Games'), ('H', 'Hardware')], default='P', max_length=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('AU', 'Autor'), ('UC', 'Usuário comum')], default='UC', max_length=13),
        ),
    ]
