# Generated by Django 4.1.5 on 2023-01-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categorias_alter_postagem_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='categoria',
            field=models.CharField(choices=[('P', 'Programação'), ('G', 'Games'), ('H', 'Hardware')], default='P', max_length=11),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
