# Generated by Django 4.1.5 on 2023-01-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_categorias_alter_postagem_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='foto_postagem',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
