# Generated by Django 4.1.5 on 2023-01-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postagem_foto_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorias', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(editable=False, max_length=30, unique=True),
        ),
    ]
