# Generated by Django 4.1.5 on 2023-01-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_alter_postagem_foto_postagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorias",
            name="categoria",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
