# Generated by Django 4.1.5 on 2023-01-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_categorias_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Comentario", models.TextField(max_length=100)),
                ("criadoEm", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=False)),
                (
                    "postagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.postagem"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.usuario"
                    ),
                ),
            ],
        ),
    ]
