# Generated by Django 4.1.5 on 2023-01-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="postagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="blog.postagem",
            ),
        ),
    ]
