# Generated by Django 4.1.5 on 2023-01-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_rename_comentario_comentario_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="foto_postagem",
            field=models.ImageField(blank=True, upload_to="fotos/%d/%m/%Y/"),
        ),
    ]
