# Generated by Django 4.1.5 on 2023-01-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_postagem_foto_postagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="foto_postagem",
            field=models.ImageField(
                blank=True,
                default="fotos/post_sem_foto.webp",
                upload_to="fotos/%d/%m/%Y/",
            ),
        ),
    ]
