# Generated by Django 4.1.5 on 2023-01-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_alter_postagem_foto_postagem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="nivel_acesso",
            new_name="tipo",
        ),
    ]
