# Generated by Django 4.1.5 on 2023-01-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_rename_nivel_acesso_usuario_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="tipo",
            new_name="nivel_acesso",
        ),
    ]
