# Generated by Django 4.1.5 on 2023-01-19 20:00

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_alter_postagem_foto_postagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="foto_postagem",
            field=models.ImageField(
                default=blog.models.default_foto_postagem, upload_to="fotos/%d/%m/%Y/"
            ),
        ),
    ]
