# Generated by Django 4.1.5 on 2023-01-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0032_alter_postagem_foto_postagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="foto_postagem",
            field=models.ImageField(
                default="fotos/programacao.jpg", upload_to="fotos/%d/%m/%Y/"
            ),
        ),
    ]
