# Generated by Django 4.1.5 on 2023-01-20 19:03

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0035_alter_postagem_foto_postagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="foto_postagem",
            field=models.ImageField(
                blank=True,
                default=blog.models.default_foto_postagem,
                upload_to="fotos/%d/%m/%Y/",
            ),
        ),
    ]
